### PR TITLE
Sync using actual default branch

### PR DESCRIPTION
**Pull request by ahmedalhulaibi**
Addressing #352 

This adds go-git as a dependency and uses it to fetch `HEAD` and the default branch name. This way this project can support any default branch `main`, `master`, `dev`, etc.

### CODE REVIEW

**Comment by ahmedalhulaibi** [comment]
This should also address #354

**Comment by ahmedalhulaibi** [comment]
@shawnps @hermanschaaf any chance this can get a review?

**Review by georgettica — APPROVED** [review]
Looks alright to me without actually testing the code :)

I hope that helps

**Comment by ahmedalhulaibi** [comment]
This should also address #357

**Comment by shawnps** [comment]
@ahmedalhulaibi we're now using the Go module proxy to download .zip files of module contents, so this git code doesn't exist anymore. Thanks for the contribution but I'm going to go ahead and close this PR.

**Comment by georgettica** [comment]
@shawnps could you then deprecate this repo and make this in the README?
I would want anyone using this tool to not go on this rabbit hole aswell

**Comment by shawnps** [comment]
@georgettica sorry, deprecate the repo? 

Since we're using the Go module proxy to download module contents, branch name doesn't matter anymore. Let me know if you have any questions about that.

**Comment by georgettica** [comment]
Oh sorry, I thought it was a different PR entirely (lost my context)
Oki!
Thanks :)

**Comment by shawnps** [comment]
@georgettica no worries! Feel free to open issues if you have any other requests 😄

**Comment by georgettica** [comment]
I'll reopen and tag you :)

**Pull request closed without merging**
