### PR TITLE
Making the Check Repo analysis logic re-usable

### PR DESCRIPTION
**Pull request by tariq1890**

### CODE REVIEW

**Comment by tariq1890** [comment]
@shawnps @hermanschaaf

**Comment by shawnps** [comment]
@tariq1890 just FYI, we've been having a lot of issues on the server recently, and we reverted this change to see if it's related. I'm wondering if maybe the boltdb is not closing properly.

**Comment by tariq1890** [comment]
Sure! I'll have a look as well.

**Comment by tariq1890** [comment]
Still trying to find out why this would cause an issue. Do you have any server logs that will help with the analysis?

**Pull request merged**
