### PR TITLE
Allow user to change hostname and port.

### PR DESCRIPTION
**Pull request by smcquay**
I wanted to test this out on a different machine on my house and added this code so that I could.

### CODE REVIEW

**Comment by shawnps** [comment]
@smcquay this is a good idea, but I'd prefer it be a flag rather than environment variables (something like this):

```
goreportcard -h 127.0.0.1:8080
```

**Comment by smcquay** [comment]
I'm happy to change it to the way you spelled it with flags, however I was just considering that it's a server app and likely will run as a daemon. According to 12factor.net:

http://12factor.net/config

> "The twelve-factor app stores config in environment variables

Thoughts on me pluming both through? default to environment, override with flags?

**Comment by hermanschaaf** [comment]
I tend to agree with Shawn here. By using flags, nothing stops you from still storing config in environment variables, as in:

```
godep go run main.go -h $HOST
```

And then people are free to use whatever environment variable they want, and it won't conflict with something else they already have (especially for a common name like `$HOST`). If you are running it through the makefile, then yes, the only way is probably to add an environment variable in there with a sensible default, like,

```
GRC_HOST = ':8080'
```

and then

```
start:
	godep go run main.go -h $(GRC_HOST)
```

which means you can override it on the command line with:

```
make -e GRC_HOST='0.0.0.0:8888' start
```

I think that gives us the best of both worlds: Go code stays clean and non-specific, using only the `-h` flag, and the makefile, which is optional to use anyway, can be supplied with an environment variable.

**Comment by smcquay** [comment]
There are various spellings for this in the tools that exist. I did not go with -h as that collides with -help. I chose to match the godoc tool.

Let me know what you think.

**Comment by shawnps** [comment]
Cool that lgtm, thanks @smcquay, sorry if it wasn't quite what you wanted but I like this.

**Comment by shawnps** [comment]
@hermanschaaf when you get a chance wanna take a look and merge if it looks good to you?

**Comment by hermanschaaf** [comment]
Looks good to me, thanks @smcquay!

**Pull request merged**
