### PR TITLE
Update report.html

### PR DESCRIPTION
**Pull request by ti**
badge scheme adapted form current url (support http scheme)

### CODE REVIEW

**Comment by ti** [comment]
@shawnps this is used for personal deployment。 can you merge it?

**Comment by ti** [comment]
@shawnps this  is useful for self deployment。 can you accept this request ?

**Comment by shawnps** [comment]
@ti just so I'm understanding correctly, this allows you to run GRC without https on your local environment, and you are passing in your own domain with the `-domain` flag?

**Comment by shawnps** [comment]
@hermanschaaf thoughts on this?

**Comment by ti** [comment]
@shawnps  yes,  I run it in -domain flag, but the images need http scheme

**Pull request closed without merging**
