### PR TITLE
Support Shields IO badge styles

### PR DESCRIPTION
**Pull request by Tomohiro**
I'd like to get a custom style badge.

Default: `https://goreportcard.com/badge/github.com/Tomohiro/go-gyazo`:

Add style query: `https://goreportcard.com/badge/github.com/Tomohiro/go-gyazo?style=flat-square`:

### CODE REVIEW

**Comment by shawnps** [comment]
@Tomohiro thanks, LGTM

**Comment by shawnps** [comment]
@Tomohiro could you try again and let me know if it works? Seems to be working for me:

https://goreportcard.com/badge/github.com/Tomohiro/go-gyazo?style=flat-square

**Comment by Tomohiro** [comment]
@shawnps It works! Thank you!

**Comment by shawnps** [comment]
@Tomohiro thanks for the PR!

**Pull request merged**
