### PR TITLE
#215 moved creation of checks to callback function in main.go

### PR DESCRIPTION
**Pull request by aweisser**
This fixes issue #215

### CODE REVIEW

**Comment by shawnps** [comment]
@aweisser would you mind explaining? It's not clear to me what problem this is solving.

**Comment by aweisser** [comment]
No problem. Just convinience. 
The set of checks that should be ececuted during runtime is something that probably changes over time. There is at least one github asking for this. Plus: there is already a commented errcheck in the code. From my point of view the set if checks should be part of the application bootstrap (main.go) and should not be burried in the private depths of the handlers package. Having this configurable in the main makes it easier to understand and change.

**Comment by aweisser** [comment]
I would go even further and move the weight factors of the checks to the same place so that it's easy to configure different scenarios without messing with the core domain.

**Comment by GoLangsam** [comment]
@shawnps & @aweisser 
While refactoring for other reasons ( #207 ), I contemplated to move all `http.HandleFunc`s down into some init function of the `handlers` package, and to keep `main` as simple, stupid and agnostic as possible.

As `handlers/checks.go' imports the package `check` and builds a slice `[]check.Check` here might be a good place to consolidate the weight factors.

**Comment by aweisser** [comment]
The main.go should indeed be small and consise.
And it should have a clear bootstraping concern:
Configure and assemble all necessary components and start the application.

The handlers package represents the http part of the application.
The check package represents the core domain.

From a seperation of concerns point of view I put the question about "which checks should be included in this app process" to the "bootstrap" part, thus main.go.

Only my 5 cent. ;)
No offense.

**Comment by hermanschaaf** [comment]
Looks good to me, and thanks for the change. We can definitely do with some code cleanup. The `NewCheckHandler` that takes a func as argument is maybe a bit clunky, but I can see why it's necessary right now. One step at a time :)

**Comment by hermanschaaf** [comment]
@shawnps what do you think, good to merge?

**Comment by aweisser** [comment]
The callback is a bit clunky. That's true. I first thought about doing it more decleratively but I'd have to insert some reflection or dispatchingfor that. It this isn't cool.

**Comment by GoLangsam** [comment]
@aweisser Hallo Landsmann

No offense felt here :-)
I'll be happy and eager to have a look over the weekend - and add my three cents, if need ;-)

**Comment by GoLangsam** [comment]
@aweisser I am sorry to disagree: "Configure and assemble all necessary components" is not necessarily the raison d' ètre of a `main.go`

Packages may have their own "intelligence" to config and assemble.
They even *should* - "separation of concerns" as You said.

And: the implementation changes the topology of the (explicitly) imported packages.
And thus: Who knows what about whom. (I consider this important.)

In the existing design, `main.go` just knows about the `handlers` - does not know nor care about (one of) these using another `check` (or `download`) package.
(And that's fine with me - it's a web server. If I need to know more, I've got to study the package used.)

I see no reason for this being changed. The opposite is true, I'd even rather move the `initDB` down into `handlers` and call it from `func init()` - as neither do I see any need for `main.go` that somewhere inside a persistent store is used. But tastes may differ.

Just: it is not decidable to me: neither package has any doc which teaches the purpose (and limit) of it's concerns. How autonomous it is intended to be. Thus, I'll be happy to listen to the authors. @shawnps & @hermanschaaf

I am *not* saying that I would - same as You - like to see the the weight factors of the checks in the very same place where the checks are assembled ... and more.

Just my small cent - no intention to offend or to block refactoring & progress.

**Comment by aweisser** [comment]
@GoLangsam - Thanks for your review and opinion. I don't want to be dogmatic here, but it's important for me to understand the core principles of your application and component design. So here are some more opinions. ;)

>> Packages may have their own "intelligence" to config and assemble.
This is absolutely ok if (and only if) you want your packages to be less reusable but more usable out of the box. 

>> Who knows what about whom. (I consider this important.)
Absolutely agree. A clear and consise dependency structure between packages/components is absolutely critical for a changable and evolvable software design.

To make this valuable you have to have a clear semantics of every single package. 
Please ask yourself: What is the purpose of the handlers package right now?
What is the concern of the check package?
What is the concern of the main.go?

Another issue is visibility and scoping. There are some parts in the code where this is not clear. 

I can (if it's in your interest) contribute a bunch of refactorings that aim a seperation of the core domain model and business logic, the application logic and the concrete technology components.

- The Domain is about Checks and Scores and Cards and Sourcecode or Repos and so on.
- App is about having a Server and Controllers, a Cache of executed Checks and things like that.
- Technology is about talking to the outside world with active frontend components (http, html) and passive backend components  (boltdb, vcs). Those are concrete (but replacable) technology choices.

All in all this an adoption of the Clean Architecture proposed by Uncle Sam and influenced by the Ports&Adapters principle.

So. Just another bunch of cents. If we collect further we'll have some euros/dollars at the end. :)

**Comment by GoLangsam** [comment]
@aweisser Moin Landsmann - First: thx a lot for Your constructive thoughts and questions.
And very happily do I agree with Your principles and remarks.

Just - to avoid misunderstanding - I am not in a position to answer - and hesitate to give 'my view'.

The first word here is with the "owners" and authors. @shawnps & @hermanschaaf,
( I'm just -like You- trying to give a helping hand here, as I'm a happy user of the service. )

Let me confess: I am ***very*** dogmatic! My favorite is, *not* to follow any dogma (unless I established it myself). And: I (also) love to refactor for the better, even so in my professional career this often raised conflicts with payroll-counting, shortsighted management.

> Another issue is visibility and scoping. There are some parts in the code where this is not clear.

Very true. Just: this piece of soft does not look to me like something made for careful readers such as us, It originates from two friends having fun two years ago to come up with the initial version during a gopher meeting. And the jury was quite impressed with the user experience!

And now they find themselves with exponential growth of their users ...
And many issues, which are just time-eating 'hot-line' tasks ... 
But who am I to tell? Let's wait for them to share with us. :-)

**Comment by aweisser** [comment]
Hey. I love the idea and ux of this project, that's why I'm happy if I can help to make it even better. 
We just need a chared understanding of what it should look like.  Let's see.

**Pull request closed without merging**
