### PR TITLE
feat: using shields.io for all badges

### PR DESCRIPTION
**Pull request by caarlos0**
so we can use all styles (like the new `for-the-badge` one). 

cc/ @shawnps @hermanschaaf

### CODE REVIEW

**Comment by caarlos0** [comment]
ping?

**Comment by brpaz** [comment]
I am really interested in the "for-the-badge" style.

**Comment by shawnps** [comment]
A long time ago we switched from using shields.io because people's badges were getting cached. I think shields.io was not setting Cache-Control headers to prevent that from happening. I'll have to investigate to see if that's changed.

**Comment by nightah** [comment]
@shawnps is there any interest in moving this PR forward?
I'm interested in this PR and potentially expanding this so it can accept other parameters like `logo`.

Also, please forgive my ignorance if I'm misunderstanding something here but from what I can see the badge URL's technically wouldn't change from `https://goreportcard.com/badge/...` so the caching of the static badges wouldn't actually matter because the logic to determine the score is still going to be executed locally. The redirect to shields.io is simply to serve the static badge after the logic to determine said badge and report score has been executed.

**Comment by caarlos0** [comment]
eh ¯\_(ツ)_/¯

**Pull request merged**
