### PR TITLE
fix issue #223: It will download fail if dest repository's default branch is not ‘master’

### PR DESCRIPTION
**Pull request by vipally**
fix issue #223: It will download fail if dest repository's default branch is not ‘master’

### CODE REVIEW

**Comment by hermanschaaf** [comment]
Ideally we would pull the repository's default branch, instead of forcing `master`. I think pulling master when the default branch is something else is bound to cause even more confusion than the current error message. This doesn't look like it would be an easy thing to do though...

**Comment by vipally** [comment]
I agree your sense to pull branch ‘default’ rather than ‘master’.
The main problem of this issue is that current branch is not always 'master':
Create https://github.com/vipally/binary
cd .
git clone --depth 1 https://github.com/vipally/binary test_downloads\github.com\vipally\binary
Cloning into 'test_downloads\github.com\vipally\binary'...
cd test_downloads\github.com\vipally\binary
git status
On branch develop
Your branch is up-to-date with '**origin/develop**'.
nothing to commit, working tree clean
cd test_downloads\github.com\vipally\binary
**git checkout master**
# cd test_downloads\github.com\vipally\binary; git checkout master
error: pathspec 'master' did not match any file(s) known to git.

**Comment by vipally** [comment]
Would you mind if I push another pullrequest to fix this issue like this?
Create https://github.com/vipally/binary
cd .
**git clone --depth 1** https://github.com/vipally/binary test_downloads\github.com\vipally\binary
Cloning into 'test_downloads\github.com\vipally\binary'...
cd test_downloads\github.com\vipally\binary
git status
On branch develop
Your branch is up-to-date with '**origin/develop**'.
nothing to commit, working tree clean

cd test_downloads\github.com\vipally\binary
**git checkout**
Your branch is up-to-date with '**origin/develop**'.

**Comment by shawnps** [comment]
Should be fixed in https://github.com/gojp/goreportcard/commit/d16ec21ff2895bec4c8a977570d97a6e23e88cd4

**Comment by halink0803** [comment]
I still get this error. What should I do to resolve it. I use go get as readme say and it should get the latest version of repository, right?

**Pull request closed without merging**
