### PR TITLE
Use GolangCI-Lint

### PR DESCRIPTION
**Pull request by davidporos92**
I've replaced the deprecated [Go Meta Linter](https://github.com/alecthomas/gometalinter) with [GolangCI-Lint](https://github.com/golangci/golangci-lint).

### CODE REVIEW

**Comment by shellfu** [comment]
Hey. Any reason why this PR cannot be merged? This is a great tool but reliance on a deprecated dependency is a show stopper in some security-oriented shops.

**Comment by aneeskA** [comment]
@hermanschaaf Can you please merge this PR please unless there are any other concerns? Thanks in advance.

**Comment by hermanschaaf** [comment]
Hi, just FYI I have concerns over the license of golang-ci, since it is
essentially the basis of a competing paid product. I heard they recently
changed their license, but will need to look into this again.

**Comment by titouanfreville** [comment]
@hermanschaaf The licence was changed from AGPL to GPL. It is free to use for any  usage but do not grant reliability/warranty. It should be ok to use it here, shouldn't it ?

**Comment by aneeskA** [comment]
@hermanschaaf Can you please explain your discomfort with this? My understanding of GPL is that it is the most liberating of all license schemes.

**Comment by aneeskA** [comment]
@hermanschaaf @shawnps Can we have a closure on this please?

**Comment by l0nax** [comment]
@hermanschaaf @shawnps Any updates on this PR?

**Comment by shellfu** [comment]
+1

**Comment by Wulthan** [comment]
@hermanschaaf @shawnps Is there a reason this still hasn't been merged yet? It would be great to get an update on this.

**Comment by codenoid** [comment]
how

**Comment by danielb42** [comment]
... so?

**Review by aneeskA — APPROVED** [review]

**Comment by tariq1890** [comment]
@hermanschaaf @shawnps 

> Hi, just FYI I have concerns over the license of golang-ci, since it is
essentially the basis of a competing paid product. I heard they recently
changed their license, but will need to look into this again.

Golangci-lint's paid version is now defunct. Does this change things? I don't think their licensing should be of concern tbh

**Comment by shawnps** [comment]
Hello everyone, I think I've put off responding to this for long enough 😄 

I (and I think I can speak for @hermanschaaf as well but he can comment if he wants) am not a user of golangci-lint nor do I see the benefit of migrating the codebase to use it.

At the end of the day either @hermanschaaf or I have to deploy https://goreportcard.com. This may seem like a trivial change, but I have learned over years of maintaining GRC that even a small change can create hours of work if something fails. We don't have the benefit of a staging environment as that would cost money. We are lucky to have the cost of our one server covered by the kind folks at DigitalOcean.

I understand gometalinter is no longer maintained, but I'm not seeing the urgency to merge this. If anything I would prefer to have each linter run individually. However there are bigger priorities in my mind, such as downloading packages via a module index rather than using version control. It's unclear when we'll even have time to work on that.

I apologize for the delay in responding but I want to set expectations that it's unlikely we'll be migrating to golangci-lint anytime soon.

**Comment by titouanfreville** [comment]
Thanks for the reply. I get the concern for the automation on the website, but having to install a deprecated library to use it on custom private project can block some people from using the project... Do you think it is possible to split the project between a website public version and a custom implementation on private repository ? 

PS: willing to help for migration to module and other stuff, I'll take a look if you don't mind :)

**Comment by titouanfreville** [comment]
@shawnps while working on the usage of go modules to manage dependencies, I noticed that the script to install gometalinter (using make task) does not seems to work any more. I think it is related to the way the installation is currently processed but still some more investigation. At least the `go get` way does not seems to work for me. Could be a valid argument to switch to golang-ci, isn't it ? ^^

**Comment by tommyalatalo** [comment]
It's time to update to golangci-lint for real, just bite the bullet and fix whatever problems might arise (or not) when deploying a new version to the site. Hanging on to deprecated dependencies is not a way forward.

**Comment by JamieDavidson** [comment]
Another comment asking for a merge, love the project but can't (or I guess won't) generate reports for private projects as long as the dependency on gometalinter exists.

**Comment by shellfu** [comment]
+1

**Comment by rodrigopavan** [comment]
+1

**Comment by obalunenko** [comment]
+1

**Comment by codenoid** [comment]
what

**Pull request closed without merging**
